#
# Build CI file for Docker container
# Change the variables in this section to match your project
#

name: Account Server - CI Docker Container

on:
  push:
  pull_request:
    branches: ["master"]    
  workflow_dispatch:

jobs:
  build:
    name: Build Docker Image
    uses: DarkFactorAS/Infrastructure/.github/workflows/infrastructure-server-ci.yml@v1.1
    with:
      project_path: "./AccountServer"
      project_name: "AccountServer"
    secrets: inherit
