# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Account Client - CI Build

on:
  push:
    paths:
      - 'AccountClient/**'
      - 'AccountCommon/**'
      - '.github/workflows/accountclient_ci.yml'
      - '.github/workflows/accountclient_deploy.yml'

  pull_request:

# Environment variables used in the workflow
env:
  # Dynamic environment variables
  PROJECT_NAME: AccountClient

  # Static environment variables
  ASPNETCORE_ENVIRONMENT: Production
  BUILD_TIMEOUT: 15

jobs:
  build:

    runs-on: ubuntu-latest

    # Build steps
    steps:

    # Check out code from the repository
    - name: Checkout repository
      uses: actions/checkout@v4    

    # Build Account Client
    - name: Add GitHub nuget repository
      run: dotnet nuget update source DarkFactorAS --username ${{ secrets.NUGET_USERNAME }}  --password ${{ secrets.NUGET_TOKEN }} --store-password-in-clear-text --configfile "${{ env.PROJECT_NAME }}/NuGet.config"

    - name: AccountClient - Restore dependencies
      run: dotnet restore ${{ env.PROJECT_NAME }}/${{ env.PROJECT_NAME }}.csproj

    - name: AccountClient - Build
      run: dotnet build ${{ env.PROJECT_NAME }}/${{ env.PROJECT_NAME }}.csproj --no-restore --configuration ${{ env.ASPNETCORE_ENVIRONMENT }}
