#
# Build Deploy file for Docker container
# Change the variables in this section to match your project
#

name: Account Server - Deploy New

defaults:
  run:
    working-directory: .

#
# Everything below this is template code
#

on:
  release:
    types: [published]

  push:

  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

jobs:
  staging:
    name: Deploy to Staging
    uses: ./.github/workflows/accountserver_deploy_step.yml
    with:
      environment: staging
    secrets: inherit
    vars: inherit

  # production:
  #   name: Deploy to Production
  #   uses: ./.github/workflows/accountserver_deploy_step.yml
  #   with:
  #     environment: production
  #   secrets: inherit
  #   vars: inherit
  #   # Run this job only after the staging job is done
  #   needs: staging
