#
# Build CI file
# Change the variables in this section to match your project
#

name: Account Client - CI Build
env:
  PROJECT_NAME: AccountClient
  CONFIGURATION: Release

defaults:
  run:
    working-directory: ./AccountClient

#
# Everything below this is template code
#

on:
  push:
  workflow_dispatch:
  pull_request:
    branches: ["master"]

jobs:
  build:

    # Timeout for the job
    timeout-minutes: 15

    runs-on: ubuntu-latest

    # Build steps
    steps:

    # Check out code from the repository
    - name: Checkout repository
      uses: actions/checkout@v4    

    # Build Account Client
    - name: Add GitHub nuget repository
      run: dotnet nuget update source DarkFactorAS --username ${{ secrets.NUGET_USERNAME }}  --password ${{ secrets.NUGET_TOKEN }} --store-password-in-clear-text --configfile "NuGet.config"

    - name: ${{ env.PROJECT_NAME }} - Restore dependencies
      run: dotnet restore ${{ env.PROJECT_NAME }}.csproj

    - name: ${{ env.PROJECT_NAME }} - Build
      run: dotnet build ${{ env.PROJECT_NAME }}.csproj --no-restore --configuration ${{ env.CONFIGURATION }}
