#
# Build CI file for Docker container
# Change the variables in this section to match your project
#

name: Account Server - CI Docker Container

on:
  push:
    paths:
      - 'AccountServer/**'
      - 'AccountCommon/**'
      - 'Dockerfile'
      - 'docker-compose.yml'
      - '.github/workflows/accountserver_docker_ci.yml'
  pull_request:
    branches: ["master", "main"]
  workflow_dispatch:

jobs:
  build:
    name: Build Docker Image
    uses: DarkFactorAS/Infrastructure/.github/workflows/infrastructure-server-ci.yml@v1.1
    with:
      project_path: "./AccountServer"
      project_name: "AccountServer"
      dockerfile: "../Dockerfile"
    secrets: inherit
